# Generated by Django 5.0.6 on 2024-05-14 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_cart_id_alter_cart_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='uuid',
            new_name='id',
        ),
    ]
