# Generated by Django 5.0.6 on 2024-05-14 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_rename_uuid_cart_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
