# Generated by Django 5.0.6 on 2024-05-16 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_customer_options_remove_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancle_order', 'Can Cancel Order')]},
        ),
    ]
